import { ChartOptions } from "./chart-data";
import { Color } from '@swimlane/ngx-charts';

export const DEFAULT_CHART_OPTIONS: ChartOptions = {
  legend: false,
  legendTitle: "Chart",
  xAxis: {},
  yAxis: {},
  showXAxis: true,
  showYAxis: true,
  showXAxisLabel: true,
  showYAxisLabel: true,
  xAxisLabel: "X-Axis",
  yAxisLabel: "Y-Axis",
  tooltipDisabled: false,
  gradient: false,
  showGridLines: true,
  activeEntries: [],
  trimXAxisTicks: true,
  trimYAxisTicks: true,
  rotateXAxisTicks: true,
  maxXAxisTickLength: 16,
  maxYAxisTickLength: 16,
  xAxisTickFormatting: {},
  yAxisTickFormatting: {},
  xAxisTicks: [],
  yAxisTicks: [],
  barPadding: 8,
  roundDomains: false,
  roundEdges: false,
  yScaleMax: 0,
  yScaleMin: 0,
  showDataLabel: true,
  dataLabelFormatting: {},
  noBarWhenZero: false,
  wrapTicks: false,
  colorScheme: { domain: ['hsl(var(--primary))'] } as Color,
  view: [0,0]
};
