import { ChartOptions } from "./chart-data";
import { Color, LegendPosition } from '@swimlane/ngx-charts';

export const DEFAULT_CHART_OPTIONS: ChartOptions = {
  legend: false,
  legendTitle: "Chart",
  legendPosition: "below" as LegendPosition,
  xAxis: {},
  yAxis: {},
  showXAxis: true,
  showYAxis: true,
  showXAxisLabel: false,
  showYAxisLabel: false,
  xAxisLabel: "",
  yAxisLabel: "",
  tooltipDisabled: false,
  gradient: false,
  showGridLines: false,
  activeEntries: [],
  trimXAxisTicks: false,
  trimYAxisTicks: false,
  rotateXAxisTicks: false,
  maxXAxisTickLength: 8,
  maxYAxisTickLength: 8,
  xAxisTickFormatting: {},
  yAxisTickFormatting: {},
  xAxisTicks: [],
  yAxisTicks: [],
  barPadding: 8,
  roundDomains: false,
  roundEdges: false,
  yScaleMax: 0,
  yScaleMin: 0,
  showDataLabel: false,
  dataLabelFormatting: {},
  noBarWhenZero: false,
  wrapTicks: false,
  colorScheme: { domain: ['hsl(var(--primary))'] } as Color,
  view: [0,0]
};
